apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dczd2d08w-dotnet-basic
  janus-idp.io/tekton: dczd2d08w-dotnet-basic
  backstage.io/kubernetes-id: dczd2d08w-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dczd2d08w-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
