apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dczd2d08w-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-8qdbs.8qdbs.sandbox2265.opentlc.com/tssc/rhtap-qe-dotnet-basic:jenkins-7e2ee9bb41d3689f1d1f5a1de8e8cb5e5b1ac21d
          name: container-image
