apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dczd2d08w-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/dczd2d08w-dotnet-basic